#!/usr/bin/env python3
"""Manifest of sandbox/ artifacts -- one row per blinded_*.json + report.

A reviewer landing on the repo needs to know:
  - which result file is the headline number
  - which is a regression check
  - which is an exploratory ablation
  - what reports / HTML / markdown go with each run

This script reads every blinded_*.json + matching evidence_*.html /
report markdown and prints a single table.

Usage:
    python scripts/sandbox_manifest.py > sandbox/MANIFEST.md
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


_SANDBOX = Path(__file__).resolve().parents[1] / "sandbox"


def _label_for(p: Path) -> str:
    """Heuristic-label a blinded result by stem."""
    s = p.stem.lower()
    if "_gpt4o" in s:    return "frontier (gpt-4o)"
    if "_llama" in s or "r1distill" in s:  return "local (R1-Distill 8B)"
    if "_sc3" in s:      return "self-consistency 3"
    if "tools" in s:     return "tool-use loop"
    if "v17" in s or "v18" in s or "v19" in s: return "ablation"
    if "v20" in s:       return "ablation"
    return "baseline"


def _summarize_blinded(p: Path) -> dict | None:
    try:
        d = json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return None
    results = d.get("results", [])
    n = d.get("n_cases") or len(results)
    hits = sum(1 for r in results if r.get("target_recovered"))
    if not n:
        return None
    return {
        "name": p.name,
        "label": _label_for(p),
        "n": n,
        "hits": hits,
        "acc": hits / n,
        "wall_min": (d.get("total_seconds", 0) or 0) / 60,
        "backend": d.get("backend", "?"),
        "dg_default_rate": d.get("disease_gene_default_rate"),
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    args = ap.parse_args()
    sys.stdout.reconfigure(encoding="utf-8")

    rows: list[dict] = []
    for p in sorted(_SANDBOX.glob("blinded_*.json")):
        s = _summarize_blinded(p)
        if s is not None:
            rows.append(s)

    print("# Sandbox manifest")
    print()
    print(f"All `blinded_*.json` files in `sandbox/` "
          f"with a one-line headline. {len(rows)} runs.")
    print()
    print("| File | Label | Backend | N | Hits | Acc | Wall (min) | DG-default rate |")
    print("|---|---|---|---|---|---|---|---|")
    for r in rows:
        dg = (f"{r['dg_default_rate']*100:.0f}%"
              if r["dg_default_rate"] is not None else "—")
        print(f"| `{r['name']}` | {r['label']} | {r['backend']} | {r['n']} | "
              f"{r['hits']} | {r['acc']:.2f} | {r['wall_min']:.1f} | {dg} |")

    # Companion files in sandbox/.
    print()
    print("## Companion reports")
    print()
    companions = [
        ("DIVERSITY.md", "Dataset diversity per split"),
        ("COST_FRONTIER.md", "Cost-vs-accuracy frontier"),
        ("RESULTS_FRONTIER.md", "Model + pipeline ablation table"),
    ]
    for fname, desc in companions:
        p = _SANDBOX / fname
        if p.exists():
            print(f"- [`sandbox/{fname}`](./{fname}) -- {desc}")

    html_reports = sorted(_SANDBOX.glob("evidence_*.html"))
    if html_reports:
        print()
        print("## Evidence-trace HTML (per-case)")
        print()
        for p in html_reports:
            print(f"- [`sandbox/{p.name}`](./{p.name})")

    print()
    print("Generated by `scripts/sandbox_manifest.py`.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
